name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish-platforms:
    name: Publish for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: macos
            os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: target/x86_64-apple-darwin/release/libmgchecker.dylib
            # asset_name: libmgchecker.dylib
            platform: platforms/libmgchecker-darwin-x64
            cross: false
          - name: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: target/x86_64-unknown-linux-gnu/release/libmgchecker.so
            # asset_name: libmgchecker.so
            platform: platforms/libmgchecker-linux-x64
            cross: false
          - name: linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: target/aarch64-unknown-linux-gnu/release/libmgchecker.so
            # asset_name: libhellorust.so(aarch64)
            platform: platforms/libmgchecker-linux-arm64
            cross: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: ${{ matrix.cross }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --target ${{ matrix.target }} --release

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Npm Publish
        run: |
          cp ${{ matrix.artifact_name }} ${{ matrix.platform }}/index.node
          cd ${{ matrix.platform }}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLIST_TOKEN }}

  publish-npm:
    name: Publish Npm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Npm Publish
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLIST_TOKEN }}
